language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-coffee-module' ]; then cd .. && eval "mv $currentfolder generator-coffee-module" && cd generator-coffee-module; fi
